spring.application.name=ncis


#DB configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/Looop_NCIS
spring.datasource.username=postgres
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#app.crypto.key=jpsg4tdugu
app.reference-date=20240101
